# Generated by Django 3.1.4 on 2020-12-07 02:42

import autoslug.fields
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='courses/')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('duration', models.TextField(blank=True, max_length=255)),
                ('language', models.TextField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('tags', models.TextField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('previous_knowledge', ckeditor.fields.RichTextField(blank=True)),
                ('difficulty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('duration', models.TextField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('content1', ckeditor.fields.RichTextField(blank=True)),
                ('content2', ckeditor.fields.RichTextField(blank=True)),
                ('content3', ckeditor.fields.RichTextField(blank=True)),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('content1', ckeditor.fields.RichTextField(blank=True)),
                ('content2', ckeditor.fields.RichTextField(blank=True)),
                ('content3', ckeditor.fields.RichTextField(blank=True)),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.section')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.section')),
            ],
        ),
    ]
