# Generated by Django 3.1.4 on 2020-12-07 02:42

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/')),
                ('permissions', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('Z', 'enums.user_types.admin'), ('T', 'enums.user_types.teacher'), ('S', 'enums.user_types.student')], max_length=1)),
                ('state', models.CharField(choices=[('A', 'enums.states.active'), ('I', 'enums.states.inactive')], default='A', max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='email', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4)),
                ('last_password_change', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'unique_together': {('email', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('U', 'enums.authtoken_states.used'), ('P', 'enums.authtoken_states.pending')], default='P', max_length=1)),
                ('token_type', models.CharField(choices=[('P', 'enums.authtoken_types.password_change')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
